import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import Script from 'next/script'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <body className="px-8">

        <Head>
          <title>CMS</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
          {/* <script src="https://cdn.tailwindcss.com"></script> */}
        </Head>
          {/* <Script src='https://cdn.tailwindcss.com' /> */}

        <section>
          <p className= "text-4xl">
              CMS SUMMARISATION
          </p><br />
        </section>

        <section >
          <ul>
              <form className="sm:max-w-md md:max-w-2xl">
                  <label>Title</label><br />
                  <input className="outline outline-1 w-full h-10 border rounded-md p-2"></input><br /><br />

                  <label>URL</label><br />
                  <input className="outline outline-1 w-full h-10 border rounded-md p-2"></input><br /><br />

                  <label>Text</label><br />
                  <textarea className="outline outline-1 w-full h-40 resize-none border rounded-md p-2"></textarea><br /><br />

                  <label>Summary</label><br />
                  <textarea className="outline outline-1 w-full h-40 resize-none border rounded-md p-2"></textarea><br /><br />     

                  <button className="px-5 bg-cyan-600 rounded p-1 hover:bg-black hover:text-white" type="submit">Update</button><br /><br /> 
              </form>
          </ul>
        </section>
      </body>
    </>
  )
} 
